services:
  - type: web
    name: backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: node backend/index.js
    envVars:
      - key: PORT
        value: 3000
    plan: free

  - type: web
    name: frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    plan: free